### ISSUE TITLE
Feature request: Do not attempt to reconnect

### ISSUE THREAD

**Issue by thehappycoder** [ibc/protoo#10]
I've put some authorization logic inside protoo server. When auth fails, client still tries to connect again, which isn't what I want.

At the same time, once client gets connected and connection is lost, I want it to try to reconnect.

**Comment by thehappycoder** [comment]
It seems that there is such a feature already but it doesn't work the way I think it should work.

protoo-client/lib/transports/WebSocketTransport.js has the following logic:
```
// Don't retry if code is 4000 (closed by the server).
if (event.code !== 4000)
```

I want protoo server to reject connection request with `reject(4000, 'Connection denied')`, and make client never try to connect.

**Comment by ibc** [comment]
That is not how WebSocket works. If you reject (in server side) the WebSocket handshake by returning != 200 to the HTTP GET, the browser will just show "connection error", nothing else. There is no chance for the JS app to "inspect" the reason of such a rejection or connection error. Again, that's how WebSocket API+protocol works.

So, if you need to reject a WebSocket connection attempt with a specific "cause", then you must accept the WebSocket handshake and then close it after sending a custom message to the client telling the closure cause.

I understand your point, but that's not feasible using the WebSocket protocol

**Comment by thehappycoder** [comment]
That's not true. Websocket has a `close` method that accepts a code, where one can specify 4000 https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#close()

Alternatively, it is possible to use X-WebSocket-Reject-Reason for specifying reason.

**Comment by thehappycoder** [comment]
I will do `acceptRequest().close()` for now, which actually responds with close code 4000, and now client doesn't try to reconnect anymore.

**Comment by ibc** [comment]
Sorry for the delay.

> That's not true. Websocket has a close method that accepts a code, where one can specify 4000 https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#close()

Yes, but you can just use it in an already established WS connection. Here we were talking about rejecting a WS handshake request, which is just a HTTP GET request. And it does not matter how the server rejects it (which status code or HTTP headers) since the browser does not expose a JS API to inspect the HTTP rejection response.

> Alternatively, it is possible to use X-WebSocket-Reject-Reason for specifying reason.

I don't think such a header is a standard nor that browsers implement it:

https://stackoverflow.com/questions/10560591/nodejs-websockets-reject-the-connection-with-a-message
