### ISSUE TITLE
Uncaught TypeError: _this2.listenerCount is not a function

### ISSUE THREAD

**Issue by RJ0123456** [ibc/protoo#11]
My package.json file:
"protoo-client": "^3.0.0"

Browse will report error: "Uncaught TypeError: _this2.listenerCount is not a function"
bellow code report error:
if (_this2.listenerCount('message') === 0) {
	logger.error('no listeners for WebSocket "message" event, ignoring received message');

	return;
}

**Comment by ibc** [comment]
You are using webpack, right?

**Comment by ibc** [comment]
Should be fixed in 3.0.1

**Comment by ibc** [comment]
`gulp` is not an "alternative" to `webpack`. What I mean is, are you using `browserify` or `webpack` or something to "pack" your whole JS app into a single bundled JS file?

**Comment by ibc** [comment]
Also, are you running protoo-client in a web app? or in a Node app?
